# Site settings
title: QTNKSR
email: contact@quentinkaiser.be
username: QKaiser
description: "I build things ... and break others."
baseurl: ""
url: "https://quentinkaiser.be/"
# Build settings
markdown: kramdown
permalink: pretty
