# Site settings
title: QTNKSR
email: contact@quentinkaiser.be
username: QKaiser
description: "I build things ... and break others."
baseurl: ""
url: "https://quentinkaiser.be/"
# Build settings
markdown: kramdown
permalink: pretty
plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
twitter:
  username: qkaiser
  card: summary
social:
  name: Quentin Kaiser
  links:
    - https://twitter.com/qkaiser
    - https://github.com/qkaiser
