# Site settings
title: QTNKSR
email: contact@quentinkaiser.be
username: QKaiser
description: "I build things ... and break others."
baseurl: ""
#url: "https://qkaiser.github.io/"
url: "http://localhost:4000"
# Build settings
markdown: kramdown
permalink: pretty
